apiVersion: apps/v1
kind: Deployment
metadata:
  name: wa-backend
  labels:
    app: wa-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wa-backend
  template:
    metadata:
      labels:
        app: wa-backend
    spec:
      # 填写镜像
      containers:
        - name: wa-backend
          image:
          imagePullPolicy: Always
          ports:
            - containerPort: 5050
      imagePullSecrets:
        - name: coding-docker