kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pv
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
              name: es-http
            - containerPort: 9300
              name: es-transport
          volumeMounts:
            - name: nfs-storage
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: nfs-pv

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 9200
      name: es-http
    - protocol: TCP
      port: 9300
      targetPort: 9300
      nodePort: 9300
      name: es-transport
  type: NodePort

