# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build up and install to server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true

      - uses: actions/upload-artifact@v3.1.2
        name: upload to artifact
        with:
          name: backend
          path: |
            ./backend/target/backend-0.0.1-SNAPSHOT.jar
            ./run.sh
          retention-days: 1

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3.0.2
        name: download artifact
        with:
          name: backend

      - name: delete older package and script
        run: sshpass -p ${{secrets.REMOTE_PASSWORD}} ssh -o StrictHostKeyChecking=no ${{secrets.REMOTE_USERNAME}}@${{secrets.REMOTE_IP}} "cd /home/Action && rm -rf ./*"

      - name: upload jar package to server
        run: sshpass -p ${{secrets.REMOTE_PASSWORD}} scp -r -o StrictHostKeyChecking=no ./backend/target/backend-0.0.1-SNAPSHOT.jar ./run.sh ${{secrets.REMOTE_USERNAME}}@${{secrets.REMOTE_IP}}:/home/Action

  run:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: 启动项目
        run: sshpass -p ${{secrets.REMOTE_PASSWORD}} ssh -o StrictHostKeyChecking=no ${{secrets.REMOTE_USERNAME}}@${{secrets.REMOTE_IP}} "cd /home/Action && chmod +x run.sh && ./run.sh"


