# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build up and install to server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build the Docker image
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true

      - name: docker build
        run: |
          docker login -u lihanyu2003 -p Yu20030405 registry.cn-beijing.aliyuncs.com
          docker build -t wa-backend ./backend
          docker tag wa-backend registry.cn-beijing.aliyuncs.com/1328411791/wa-backend:latest
          docker push registry.cn-beijing.aliyuncs.com/1328411791/wa-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            docker pull registry.cn-beijing.aliyuncs.com/1328411791/wa-backend:latest
            docker stop wa-backend
            docker rm wa-backend
            docker run -d --name wa-backend -p 5050:5050 registry.cn-beijing.aliyuncs.com/1328411791/wa-backend:latest
